require('jollyjerr.plugins.theme')
require('jollyjerr.plugins.feline')
require('jollyjerr.plugins.autopairs')
require('jollyjerr.plugins.telescope')
require('jollyjerr.plugins.fugitive')
require('jollyjerr.plugins.cmp')
require('jollyjerr.plugins.diffview')
require('jollyjerr.plugins.yoink')
