require('jollyjerr.lsp.lua')
require('jollyjerr.lsp.go')
require('jollyjerr.lsp.typescript')
require('jollyjerr.lsp.tailwindcss')
require('jollyjerr.lsp.eslint')
require('jollyjerr.lsp.svelte')
require('jollyjerr.lsp.elixir')
require('jollyjerr.lsp.rust')
